//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarStoreAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarInfo()
        {
            this.CarTypes = new HashSet<CarType>();
        }
    
        public int CarId { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public int YearMade { get; set; }
        public string Gear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarType> CarTypes { get; set; }
    }
}
