//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarStoreAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarStoreDataEntities : DbContext
    {
        public CarStoreDataEntities()
            : base("name=CarStoreDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarInfo> CarInfoes { get; set; }
        public virtual DbSet<CarLocation> CarLocations { get; set; }
        public virtual DbSet<CarsImage> CarsImages { get; set; }
        public virtual DbSet<CarType> CarTypes { get; set; }
        public virtual DbSet<RegisterUser> RegisterUsers { get; set; }
        public virtual DbSet<RentTable> RentTables { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
    }
}
