//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarStoreAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarType()
        {
            this.RentTables = new HashSet<RentTable>();
        }
    
        public int CarId { get; set; }
        public string Available { get; set; }
        public int PriceForDay { get; set; }
        public int LatePay { get; set; }
        public string CarNum { get; set; }
        public int Location { get; set; }
        public int CarInfoId { get; set; }
    
        public virtual CarInfo CarInfo { get; set; }
        public virtual CarLocation CarLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentTable> RentTables { get; set; }
    }
}
